In [1]:
import tensorflow as tf

2024-06-25 14:10:24.688948: E external/local_xla/xla/stream_executor/cuda/cuda_dnn.cc:9261] Unable to register cuDNN factory: Attempting to register factory for plugin cuDNN when one has already been registered
2024-06-25 14:10:24.688969: E external/local_xla/xla/stream_executor/cuda/cuda_fft.cc:607] Unable to register cuFFT factory: Attempting to register factory for plugin cuFFT when one has already been registered
2024-06-25 14:10:24.689739: E external/local_xla/xla/stream_executor/cuda/cuda_blas.cc:1515] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered
2024-06-25 14:10:24.693704: I tensorflow/core/platform/cpu_feature_guard.cc:182] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: AVX2 FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.
2024-06-25 14:10:25.193454: W tensorflow/compiler/tf2

In [2]:
a = tf.constant([[[1, 2, 3], [4, 5, 6], [7, 8, 9]],[[10, 11, 12], [13, 14, 15], [16, 17, 18]]], dtype=tf.float32)

2024-06-25 14:10:25.565274: I external/local_xla/xla/stream_executor/cuda/cuda_executor.cc:901] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero. See more at https://github.com/torvalds/linux/blob/v6.0/Documentation/ABI/testing/sysfs-bus-pci#L344-L355
2024-06-25 14:10:25.609716: I external/local_xla/xla/stream_executor/cuda/cuda_executor.cc:901] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero. See more at https://github.com/torvalds/linux/blob/v6.0/Documentation/ABI/testing/sysfs-bus-pci#L344-L355
2024-06-25 14:10:25.609882: I external/local_xla/xla/stream_executor/cuda/cuda_executor.cc:901] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero. See more at https://github.com/torvalds/linux/blob/v6.0/Documentation/ABI/testing/sysfs-bus-pci#L344-

In [4]:
# Make a convolutional layer to work on a
x = tf.expand_dims(a, 3)
print(x.shape)
x = tf.keras.layers.Conv2D(32, (2, 2), padding='valid', kernel_initializer=tf.constant_initializer(1))(x)
x.shape

(2, 3, 3, 1)


2024-06-25 12:36:58.950535: I external/local_xla/xla/stream_executor/cuda/cuda_dnn.cc:454] Loaded cuDNN version 8900


TensorShape([2, 2, 2, 32])

: 

In [22]:
tf.keras.layers.Conv1D(3, 1, activation='relu', input_shape=(3, 3), dtype=tf.float32)(a)

<tf.Tensor: shape=(2, 3, 3), dtype=float32, numpy=
array([[[ 2.1222537,  4.8115664,  1.0461004],
        [ 4.065755 , 12.462979 ,  2.0382814],
        [ 6.0092564, 20.114393 ,  3.030463 ]],

       [[ 7.9527583, 27.765806 ,  4.0226445],
        [ 9.89626  , 35.417217 ,  5.0148263],
        [11.839761 , 43.068634 ,  6.0070066]]], dtype=float32)>

In [6]:
x = tf.keras.layers.Flatten()(a)
tf.keras.layers.RepeatVector(3)(x)


<tf.Tensor: shape=(2, 3, 9), dtype=float32, numpy=
array([[[ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9.],
        [ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9.],
        [ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9.]],

       [[10., 11., 12., 13., 14., 15., 16., 17., 18.],
        [10., 11., 12., 13., 14., 15., 16., 17., 18.],
        [10., 11., 12., 13., 14., 15., 16., 17., 18.]]], dtype=float32)>

: 

In [5]:
tf.keras.layers.SimpleRNN(32, activation="relu", input_shape=(3, 3), dtype=tf.float32)(a)

<tf.Tensor: shape=(2, 32), dtype=float32, numpy=
array([[5.4135509e+00, 1.2834549e-01, 0.0000000e+00, 0.0000000e+00,
        0.0000000e+00, 9.6812320e-01, 9.5517635e+00, 1.7466903e-02,
        0.0000000e+00, 3.6406112e+00, 0.0000000e+00, 0.0000000e+00,
        0.0000000e+00, 3.2602239e+00, 1.2207098e+00, 0.0000000e+00,
        4.8534260e+00, 0.0000000e+00, 2.6985407e-02, 0.0000000e+00,
        0.0000000e+00, 0.0000000e+00, 7.6286240e+00, 0.0000000e+00,
        1.7403715e+00, 1.2346344e+00, 1.3779151e-01, 6.8859625e+00,
        0.0000000e+00, 1.0887625e+00, 0.0000000e+00, 6.9999518e+00],
       [1.5294514e+01, 0.0000000e+00, 0.0000000e+00, 0.0000000e+00,
        0.0000000e+00, 1.8691511e+00, 2.1765497e+01, 2.9912162e+00,
        0.0000000e+00, 7.7474613e+00, 0.0000000e+00, 0.0000000e+00,
        0.0000000e+00, 5.7527418e+00, 5.2640972e+00, 0.0000000e+00,
        1.2584564e+01, 0.0000000e+00, 9.1971517e-01, 0.0000000e+00,
        0.0000000e+00, 0.0000000e+00, 1.6796587e+01, 0.0000000e+00

In [17]:
tf.keras.layers.DepthwiseConv1D(2, activation='relu', input_shape=(3, 3), dtype=tf.float32)(a)

<tf.Tensor: shape=(2, 2, 3), dtype=float32, numpy=
array([[[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]]], dtype=float32)>

In [14]:
x = tf.expand_dims(a, 3)
x = tf.keras.layers.Conv2D(32, (2, 2), padding='valid', kernel_initializer=tf.constant_initializer(1))(x)
x = tf.keras.layers.Conv2D(64, (2, 2), padding='valid', kernel_initializer=tf.constant_initializer(1))(x)

<tf.Tensor: shape=(2, 1, 1, 32), dtype=float32, numpy=
array([[[[163840., 163840., 163840., 163840., 163840., 163840.,
          163840., 163840., 163840., 163840., 163840., 163840.,
          163840., 163840., 163840., 163840., 163840., 163840.,
          163840., 163840., 163840., 163840., 163840., 163840.,
          163840., 163840., 163840., 163840., 163840., 163840.,
          163840., 163840.]]],


       [[[458752., 458752., 458752., 458752., 458752., 458752.,
          458752., 458752., 458752., 458752., 458752., 458752.,
          458752., 458752., 458752., 458752., 458752., 458752.,
          458752., 458752., 458752., 458752., 458752., 458752.,
          458752., 458752., 458752., 458752., 458752., 458752.,
          458752., 458752.]]]], dtype=float32)>